import React, { useEffect, useRef, useState } from "react";
import io from "socket.io-client";

// Initialize Socket.io client
// Replace "http://localhost:5000" with your actual backend URL
const socket = io("http://localhost:5000");

export default function VideoCall() {
  // Refs for video elements and PeerConnection
  const localVideoRef = useRef(null);
  const remoteVideoRef = useRef(null);
  const pcRef = useRef(null);
  // Array to store ICE candidates received before remote description is set
  const pendingCandidates = useRef([]);

  // State variables for call management and UI
  const [isCaller, setIsCaller] = useState(false);
  const [incomingCall, setIncomingCall] = useState(false);
  const [showIncomingNotification, setShowIncomingNotification] = useState(false);
  const [callerId, setCallerId] = useState(null);
  // Hardcoded classroom ID for simplicity
  const [classroomId] = useState("room-123");
  const [cameraOn, setCameraOn] = useState(false);
  const [micOn, setMicOn] = useState(false);
  const [stream, setStream] = useState(null); // Local media stream
  const [screenSharing, setScreenSharing] = useState(false);
  const [isInCall, setIsInCall] = useState(false); // New state to track if a call is active

  // useEffect hook for socket event listeners
  useEffect(() => {
    // Join the specified classroom when component mounts
    socket.emit("joinClassroom", { classroomId });

    // Listener for incoming call offers
    socket.on("webrtc:incoming-call", ({ from, offer }) => {
      console.log("📞 Incoming call from:", from);
      setIncomingCall(true);
      setCallerId(from);
      setShowIncomingNotification(true);

      // Create peer connection if it doesn't exist
      if (!pcRef.current) createPeerConnection();
      // Store the remote offer for later processing
      pcRef.current.remoteOffer = offer;
    });

    // Listener for receiving an answer to an offer
    socket.on("webrtc:answer", async ({ from, answer }) => {
      console.log("✅ Answer received from:", from);
      if (pcRef.current) {
        // Set the remote description with the received answer
        await pcRef.current.setRemoteDescription(new RTCSessionDescription(answer));
        // Add any pending ICE candidates that arrived before the remote description was set
        pendingCandidates.current.forEach(async (c) => {
          await pcRef.current.addIceCandidate(new RTCIceCandidate(c));
        });
        // Clear pending candidates
        pendingCandidates.current = [];
      }
    });

    // Listener for receiving ICE candidates
    socket.on("webrtc:ice-candidate", async ({ candidate }) => {
      if (!candidate) return; // Ignore null candidates
      if (pcRef.current?.remoteDescription) {
        // If remote description is set, add the candidate immediately
        try {
          await pcRef.current.addIceCandidate(new RTCIceCandidate(candidate));
        } catch (err) {
          console.error("Error adding ICE candidate:", err);
        }
      } else {
        // Otherwise, store the candidate to be added later
        pendingCandidates.current.push(candidate);
      }
    });

    // Listener for when a peer hangs up
    socket.on("webrtc:hangup", () => {
      console.log("Peer has hung up.");
      // Call the hangUpCall function to clean up the local side
      hangUpCall(false); // false means it's initiated by the remote peer
    });

    // Cleanup function: remove all socket listeners when component unmounts
    return () => {
      socket.off("webrtc:incoming-call");
      socket.off("webrtc:answer");
      socket.off("webrtc:ice-candidate");
      socket.off("webrtc:hangup");
      // Ensure we hang up the call if the component unmounts
      hangUpCall(true); // true means it's initiated by component unmount
    };
  }, [classroomId]); // Dependency array ensures effect runs only once or when classroomId changes

  // Function to create a new RTCPeerConnection
  const createPeerConnection = () => {
    pcRef.current = new RTCPeerConnection({
      iceServers: [{ urls: "stun:stun.l.google.com:19302" }], // Google STUN server for NAT traversal
    });

    // Event listener for ICE candidates generated by our local peer connection
    pcRef.current.onicecandidate = (event) => {
      if (event.candidate) {
        // Emit the ICE candidate to the other peer via the signaling server
        socket.emit("webrtc:ice-candidate", { classroomId, candidate: event.candidate });
      }
    };

    // Event listener for remote tracks being added to the peer connection
    pcRef.current.ontrack = (event) => {
      console.log("🎥 Remote stream added");
      if (remoteVideoRef.current) {
        // Assign the remote stream to the remote video element
        remoteVideoRef.current.srcObject = event.streams[0];
      }
    };

    // Event listener for when the peer connection state changes (e.g., connected, disconnected)
    pcRef.current.onconnectionstatechange = () => {
      console.log("PC state:", pcRef.current.connectionState);
      if (pcRef.current.connectionState === 'disconnected' || pcRef.current.connectionState === 'failed' || pcRef.current.connectionState === 'closed') {
        // Automatically hang up if the connection state indicates a problem
        hangUpCall(false);
      }
    };
  };

  // Function to start a WebRTC call
  const startCall = async () => {
    setIsCaller(true);
    setIsInCall(true); // Set call active
    createPeerConnection(); // Create a new peer connection
    await enableCameraAndMic(); // Enable local camera and microphone
    const offer = await pcRef.current.createOffer(); // Create an SDP offer
    await pcRef.current.setLocalDescription(offer); // Set local description
    socket.emit("webrtc:offer", { classroomId, offer, to: null }); // Emit the offer to the signaling server
  };

  // Function to answer an incoming call
  const answerCall = async () => {
    setIncomingCall(false);
    setShowIncomingNotification(false);
    setIsInCall(true); // Set call active
    if (!pcRef.current) createPeerConnection(); // Ensure peer connection exists
    // Set the stored remote offer as the remote description
    await pcRef.current.setRemoteDescription(new RTCSessionDescription(pcRef.current.remoteOffer));
    // Add any pending ICE candidates now that remote description is set
    pendingCandidates.current.forEach(async (c) => {
      await pcRef.current.addIceCandidate(new RTCIceCandidate(c));
    });
    pendingCandidates.current = [];

    const answer = await pcRef.current.createAnswer(); // Create an SDP answer
    await pcRef.current.setLocalDescription(answer); // Set local description
    socket.emit("webrtc:answer", { classroomId, answer, to: callerId }); // Emit the answer
    await enableCameraAndMic(); // Enable local camera and mic for the answerer
  };

  // Function to enable local camera and microphone
  const enableCameraAndMic = async () => {
    if (!stream) {
      try {
        const localStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
        setStream(localStream);
        if (localVideoRef.current) localVideoRef.current.srcObject = localStream;
        // Add tracks from the local stream to the peer connection
        localStream.getTracks().forEach((track) => pcRef.current.addTrack(track, localStream));
        setCameraOn(true);
        setMicOn(true);
      } catch (error) {
        console.error("Error accessing camera and mic:", error);
        // You might want to show an error message to the user here
      }
    } else {
      // If stream already exists, just enable tracks
      stream.getVideoTracks().forEach((track) => (track.enabled = true));
      stream.getAudioTracks().forEach((track) => (track.enabled = true));
      setCameraOn(true);
      setMicOn(true);
    }
  };

  // Function to toggle camera on/off
  const toggleCamera = () => {
    if (stream) {
      stream.getVideoTracks().forEach((track) => (track.enabled = !track.enabled));
      setCameraOn((prev) => !prev);
    }
  };

  // Function to toggle microphone on/off
  const toggleMic = () => {
    if (stream) {
      stream.getAudioTracks().forEach((track) => (track.enabled = !track.enabled));
      setMicOn((prev) => !prev);
    }
  };

  // Function to handle screen sharing
  const shareScreen = async () => {
    if (!screenSharing) {
      try {
        // Get screen sharing stream
        const screenStream = await navigator.mediaDevices.getDisplayMedia({ video: true });
        const screenTrack = screenStream.getVideoTracks()[0];
        // Find the existing video sender and replace its track with the screen track
        const sender = pcRef.current
          .getSenders()
          .find((s) => s.track?.kind === "video");

        if (sender) {
          await sender.replaceTrack(screenTrack);
          setScreenSharing(true);

          // Listen for screen sharing end event (e.g., user stops sharing from browser UI)
          screenTrack.onended = () => {
            const currentSender = pcRef.current.getSenders().find((s) => s.track?.kind === "video");
            if (currentSender && stream) {
              currentSender.replaceTrack(stream.getVideoTracks()[0]); // Switch back to camera
            }
            setScreenSharing(false);
          };
        } else {
          console.warn("No video sender found to replace track.");
        }
      } catch (err) {
        console.error("Screen share failed:", err);
      }
    } else {
      // Stop sharing: replace screen track with camera track
      const sender = pcRef.current.getSenders().find((s) => s.track?.kind === "video");
      if (sender && stream) {
        await sender.replaceTrack(stream.getVideoTracks()[0]);
      }
      setScreenSharing(false);
    }
  };

  // Function to hang up the call
  const hangUpCall = (isLocalInitiated = true) => {
    // Stop local media tracks
    if (stream) {
      stream.getTracks().forEach((track) => track.stop());
      setStream(null);
    }

    // Close the PeerConnection
    if (pcRef.current) {
      pcRef.current.close();
      pcRef.current = null;
    }

    // Reset all call-related states
    setIsCaller(false);
    setIncomingCall(false);
    setShowIncomingNotification(false);
    setCallerId(null);
    setCameraOn(false);
    setMicOn(false);
    setScreenSharing(false);
    setIsInCall(false); // Set call inactive

    // Clear video elements
    if (localVideoRef.current) localVideoRef.current.srcObject = null;
    if (remoteVideoRef.current) remoteVideoRef.current.srcObject = null;

    // Emit hangup event to the other peer if initiated locally
    if (isLocalInitiated) {
      socket.emit("webrtc:hangup", { classroomId });
    }
  };


  return (
    <div className="min-h-screen bg-gray-100 text-gray-900 flex flex-col items-center justify-center p-4 font-inter">
      <h2 className="text-4xl font-extrabold mb-8 text-blue-600">
        <span role="img" aria-label="video camera">📞</span> WebRTC Video Call
      </h2>

      {/* Video Streams */}
      <div className="relative w-full max-w-4xl bg-white rounded-lg shadow-2xl overflow-hidden mb-8">
        <div className="flex flex-col md:flex-row gap-4 p-4">
          <div className="relative flex-1 bg-gray-200 rounded-lg overflow-hidden border-2 border-blue-400">
            <video
              ref={localVideoRef}
              autoPlay
              muted
              playsInline
              className="w-full h-full object-cover rounded-lg"
            />
            <div className="absolute bottom-2 left-2 bg-gray-200 bg-opacity-85 text-xs px-2 py-1 rounded-md text-gray-800">
              Your Stream
            </div>
          </div>
          <div className="relative flex-1 bg-gray-200 rounded-lg overflow-hidden border-2 border-green-400">
            <video
              ref={remoteVideoRef}
              autoPlay
              playsInline
              className="w-full h-full object-cover rounded-lg"
            />
            <div className="absolute bottom-2 left-2 bg-gray-200 bg-opacity-85 text-xs px-2 py-1 rounded-md text-gray-800">
              Remote Stream
            </div>
          </div>
        </div>
      </div>

      {/* Call Control Buttons */}
      <div className="mt-4 flex flex-wrap justify-center gap-4 w-full max-w-2xl">
        {/* Start Call Button */}
        {!isInCall && !incomingCall && (
          <button
            onClick={startCall}
            className="flex items-center justify-center px-6 py-3 bg-gradient-to-r from-blue-500 to-indigo-600 text-white font-semibold rounded-full shadow-lg hover:from-blue-600 hover:to-indigo-700 transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-4 focus:ring-blue-300"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
              <path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 1.48a1 1 0 01-.542 1.31L5.812 7.749A15.048 15.048 0 0012.251 14.188l1.379-.691a1 1 0 011.31.542l1.48.74A1 1 0 0118 16.847V17a1 1 0 01-1 1H3a1 1 0 01-1-1V3z" />
            </svg>
            Start Call
          </button>
        )}

        {/* Answer Call Button */}
        {incomingCall && (
          <button
            onClick={answerCall}
            className="flex items-center justify-center px-6 py-3 bg-gradient-to-r from-green-500 to-teal-600 text-white font-semibold rounded-full shadow-lg hover:from-green-600 hover:to-teal-700 transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-4 focus:ring-green-300"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM7 9a1 1 0 00-1 1v1a1 1 0 102 0v-1a1 1 0 00-1-1zm5-1a1 1 0 11-2 0 1 1 0 012 0zm-4 4a1 1 0 00-1 1v1a1 1 0 102 0v-1a1 1 0 00-1-1z" clipRule="evenodd" />
            </svg>
            Answer Call
          </button>
        )}

        {/* Controls during an active call */}
        {isInCall && (
          <>
            {/* Toggle Camera Button */}
            <button
              onClick={toggleCamera}
              className={`flex items-center justify-center px-6 py-3 font-semibold rounded-full shadow-lg transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-4
                ${cameraOn ? 'bg-orange-500 hover:bg-orange-600 focus:ring-orange-300' : 'bg-gray-400 hover:bg-gray-500 focus:ring-gray-200'} text-white`}
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
                {cameraOn ? (
                  <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v8a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2H4zm10 2a1 1 0 11-2 0 1 1 0 012 0zm-6 8a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd" />
                ) : (
                  <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4a2 2 0 012 2v4a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2-2a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2V6a2 2 0 00-2-2H6zM4.5 10a.5.5 0 00-.5.5v2a.5.5 0 00.5.5h2a.5.5 0 00.5-.5v-2a.5.5 0 00-.5-.5h-2z" clipRule="evenodd" />
                )}
              </svg>
              {cameraOn ? "Camera Off" : "Camera On"}
            </button>

            {/* Toggle Mic Button */}
            <button
              onClick={toggleMic}
              className={`flex items-center justify-center px-6 py-3 font-semibold rounded-full shadow-lg transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-4
                ${micOn ? 'bg-purple-500 hover:bg-purple-600 focus:ring-purple-300' : 'bg-gray-400 hover:bg-gray-500 focus:ring-gray-200'} text-white`}
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
                {micOn ? (
                  <path d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" />
                ) : (
                  <path fillRule="evenodd" d="M7 6a3 3 0 10-6 0v2a3 3 0 006 0V6zm-3 2v2a4 4 0 008 0V8a1 1 0 012 0v2.5A6.5 6.5 0 0110 16a6.5 6.5 0 01-6.5-6.5V8a1 1 0 012 0z" clipRule="evenodd" />
                )}
              </svg>
              {micOn ? "Mute Mic" : "Unmute Mic"}
            </button>

            {/* Share Screen Button */}
            <button
              onClick={shareScreen}
              className={`flex items-center justify-center px-6 py-3 font-semibold rounded-full shadow-lg hover:from-teal-600 hover:to-cyan-700 transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-4
                ${screenSharing ? 'bg-red-600 hover:bg-red-700 focus:ring-red-300' : 'bg-blue-600 hover:bg-blue-700 focus:ring-blue-300'} text-white`}
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm-7-8a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd" />
              </svg>
              {screenSharing ? "Stop Share" : "Share Screen"}
            </button>

            {/* Hangup Call Button */}
            <button
              onClick={() => hangUpCall(true)}
              className="flex items-center justify-center px-6 py-3 bg-gradient-to-r from-red-600 to-rose-700 text-white font-semibold rounded-full shadow-lg hover:from-red-700 hover:to-rose-800 transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-4 focus:ring-red-300"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M7.707 1.5l1.597 1.597A8 8 0 0117 10a8 8 0 01-1.597 5.903L7.707 18.5a1 1 0 01-1.414-1.414L14.086 10 6.293 2.707a1 1 0 011.414-1.414z" clipRule="evenodd" />
              </svg>
              Hang Up
            </button>
          </>
        )}
      </div>

      {/* Incoming Call Notification */}
      {showIncomingNotification && !isInCall && (
        <div className="fixed top-4 right-4 bg-yellow-200 text-gray-900 p-4 rounded-lg shadow-xl animate-bounce border-2 border-yellow-400">
          <p className="font-bold text-lg flex items-center">
            <span role="img" aria-label="bell" className="mr-2">🔔</span> Incoming Call from {callerId}!
          </p>
          <div className="mt-2 text-sm">
            Click 'Answer Call' to join.
          </div>
        </div>
      )}
    </div>
  );
}
